#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"
[[ -f .env ]] || cp .env.example .env
. "$ROOT/scripts/lib/env.sh"
hull_load_env "$ROOT/.env"
HOST="${HULL_HOST:-hull.test}"

"$ROOT/scripts/check-deps.sh" dev
"$ROOT/scripts/generate-certs.sh"
"$ROOT/scripts/render-edge.sh" dev
"$ROOT/scripts/render-brand.sh"
"$ROOT/scripts/preflight.sh"

compose() {
  docker compose --env-file "$ROOT/.env" \
    -f "$ROOT/deploy/compose.yaml" \
    -f "$ROOT/deploy/compose.dev.yaml" \
    -p hull "$@"
}

compose up -d postgres rustfs mailpit traefik
# TCP probe with consecutive successes — see the note in up.sh.
echo -n "waiting for postgres"
ready=0
for _ in $(seq 1 60); do
  if docker exec hull-pg pg_isready -h 127.0.0.1 -U "${HULL_POSTGRES_USER:-hull}" -d "${HULL_POSTGRES_DB:-hull}" >/dev/null 2>&1; then
    ready=$((ready + 1))
    if [[ "$ready" -ge 3 ]]; then
      echo " ok"
      break
    fi
  else
    ready=0
  fi
  echo -n "."
  sleep 0.5
done
if [[ "$ready" -lt 3 ]]; then
  echo " FAIL"
  echo "ERROR: postgres did not become ready" >&2
  exit 1
fi

export HULL_DATABASE_URL="postgresql://${HULL_POSTGRES_USER:-hull}:${HULL_POSTGRES_PASSWORD:-hull}@127.0.0.1:${HULL_PG_PORT:-5432}/${HULL_POSTGRES_DB:-hull}"
export HULL_SMTP_HOST=127.0.0.1
export HULL_SMTP_PORT=1025
export HULL_S3_ENDPOINT=http://127.0.0.1:9000
export HULL_PUBLIC_ORIGIN="https://app.${HOST}"
export HULL_SEED_DEMO="${HULL_SEED_DEMO:-1}"

# RustFS S3 is not published on the host in product compose. For inner loop
# the API on the host needs it — publish via a one-off note:
# talk to rustfs through `docker exec` is not an HTTP client. Map 9000.
if ! ss -ltn 2>/dev/null | grep -qE "127\\.0\\.0\\.1:9000\\s"; then
  echo "NOTE: S3 is only on the Docker network. Avatar upload in inner loop needs a published 9000 or leave HULL_S3_ENDPOINT empty."
  unset HULL_S3_ENDPOINT || true
fi

HULL_PG_CONTAINER=hull-pg \
  PGUSER="${HULL_POSTGRES_USER:-hull}" \
  PGPASSWORD="${HULL_POSTGRES_PASSWORD:-hull}" \
  PGDATABASE="${HULL_POSTGRES_DB:-hull}" \
  HULL_SEED_DEMO="${HULL_SEED_DEMO:-1}" \
  "$ROOT/scripts/migrate.sh"

# These were computed and then thrown away: the second terminal ran with the
# adapter's own defaults, so it connected to :5432 rather than HULL_PG_PORT and
# came up with mail and object storage disabled. Write them somewhere sourceable.
DEV_ENV="$ROOT/.env.dev"
{
  echo "# Generated by scripts/dev.sh — source this in the inner-loop terminals."
  echo "export HULL_HOST=${HOST@Q}"
  echo "export HULL_DATABASE_URL=${HULL_DATABASE_URL@Q}"
  echo "export HULL_SMTP_HOST=${HULL_SMTP_HOST@Q}"
  echo "export HULL_SMTP_PORT=${HULL_SMTP_PORT@Q}"
  echo "export HULL_S3_ENDPOINT=${HULL_S3_ENDPOINT:-}"
  echo "export HULL_PUBLIC_ORIGIN=${HULL_PUBLIC_ORIGIN@Q}"
  echo "export HULL_SEED_DEMO=${HULL_SEED_DEMO@Q}"
} >"$DEV_ENV"

echo
echo "DEV_OK  start these in other terminals:"
echo "  cd $ROOT/adapters/fastapi && . $DEV_ENV && uv run hull-fastapi"
echo "  cd $ROOT && HULL_HOST=${HOST} pnpm install && pnpm dev:www && pnpm dev:web && pnpm dev:admin"
echo "https://${HOST}/  https://app.${HOST}/  https://admin.${HOST}/"
